config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users
  # resources :users
  root 'plans#index'
  resources :plans, only: [:index] do
    resources :subscriptions
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subscriptions, dependent: :restrict_with_error
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan

  attr_accessor :stripe_card_token

  def save_with_token
    if valid?
      customer = Stripe::Charge.create({
          amount: plan.price * 100,
          currency: 'usd',
          description: email,
          source: stripe_card_token,
        })
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.order(:name)
  end

  def new

  end

  def show

  end

  def create

  end

  def edit

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :find_plan
  before_action :find_subscription, only: [:show, :edit, :update, :destroy]

  def index
    @subscriptions = Subscription.order(:created_at)
  end

  def show

  end

  def new
    @subscription = @plan.subscriptions.new
  end

  def create
    @subscription = @plan.subscriptions.new(subscription_params)
    if @subscription.save_with_token
    # if @subscription.save
      redirect_to [@plan, @subscription], notice: 'Thanks for subscription!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subscription.update(subscription_params)
      redirect_to [@plan, @subscription], notice: 'Successfully updated!'
    else
      render :edit
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :email, :stripe_card_token)
  end

  def find_plan
    @plan = Plan.find(params[:plan_id])
  end

  def find_subscription
    @subscription = @plan.subscriptions.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
# Welcome page
class WelcomeController < ApplicationController
  def index
    ''
  end
end

app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
  def active_controller?(controller)
    controller_name == controller ? 'active' : ''
  end

  def flash_alert
    return { 'message-type': 'notice', 'message': notice } if notice
    return { 'message-type': 'alert', 'message': alert } if alert
    {}
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_footer.haml
.footer
  .pull-right
    Example text
  %div
    %strong Copyright
    Example Company © 2014-2015

app/views/layouts/_navigation.haml
.row.border-bottom
  %nav.navbar.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
    .navbar-header
      %a.navbar-minimalize.minimalize-styl-2.btn.btn-primary{:href => "#"}
        %i.fa.fa-bars
      %form.navbar-form-custom{:action => "search_results.html", :role => "search"}
        .form-group
          %input#top-search.form-control{:name => "top-search", :placeholder => "Search for something...", :type => "text"}/
    %ul.nav.navbar-top-links.navbar-right
      %li
        %span.m-r-sm.text-muted.welcome-message Welcome to INSPINIA+ Admin Theme.
      %li.dropdown
        %a.dropdown-toggle.count-info{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-envelope
          %span.label.label-warning 16
        %ul.dropdown-menu.dropdown-messages
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                %img.img-circle{:alt => "image", :src => "img/a7.jpg"}/
              .media-body
                %small.pull-right 46h ago
                %strong Mike Loreipsum
                started following
                = succeed "." do
                  %strong Monica Smith
                %br/
                %small.text-muted 3 days ago at 7:58 pm - 10.06.2014
          %li.divider
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                %img.img-circle{:alt => "image", :src => "img/a4.jpg"}/
              .media-body
                %small.pull-right.text-navy 5h ago
                %strong Chris Johnatan Overtunk
                started following
                = succeed "." do
                  %strong Monica Smith
                %br/
                %small.text-muted Yesterday 1:21 pm - 11.06.2014
          %li.divider
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                / = image_tag('pirunseng.jpg', class: 'img-circle')
              .media-body
                %small.pull-right 23h ago
                %strong Monica Smith
                love
                = succeed "." do
                  %strong Kim Smith
                %br/
                %small.text-muted 2 days ago at 2:30 am - 11.06.2014
          %li.divider
          %li
            .text-center.link-block
              %a{:href => "mailbox.html"}
                %i.fa.fa-envelope
                %strong Read All Messages
      %li.dropdown
        %a.dropdown-toggle.count-info{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-bell
          %span.label.label-primary 8
        %ul.dropdown-menu.dropdown-alerts
          %li
            %a{:href => "mailbox.html"}
              %div
                %i.fa.fa-envelope.fa-fw
                You have 16 messages
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a{:href => "profile.html"}
              %div
                %i.fa.fa-twitter.fa-fw
                3 New Followers
                %span.pull-right.text-muted.small 12 minutes ago
          %li.divider
          %li
            %a{:href => "grid_options.html"}
              %div
                %i.fa.fa-upload.fa-fw
                Server Rebooted
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            .text-center.link-block
              %a{:href => "notifications.html"}
                %strong See All Alerts
                %i.fa.fa-angle-right
      - if user_signed_in?
        %li
          = link_to destroy_user_session_path, method: :delete do
            %i.fa.fa-sign-out
            = t('log_out')
      - else
        %li
          = link_to new_user_session_path do
            %i.fa.fa-sign-in
            = t('log_in')
      %li
        %a.right-sidebar-toggle
          %i.fa.fa-tasks

app/views/layouts/_sidebar.haml
%nav.navbar-default.navbar-static-side{:role => "navigation"}
  .sidebar-collapse
    %ul#side-menu.nav.metismenu
      %li.nav-header
        .dropdown.profile-element
          %span
            / %img.img-circle{:alt => "pirunseng", :src => "pirunseng.jpg"}
            = image_tag('pirunseng', class: 'img-circle', style: 'width: 48px; height: 48px;')
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold Pirun Seng
              %span.text-muted.text-xs.block
                Software Engineer
                %b.caret
          %ul.dropdown-menu.animated.fadeInRight.m-t-xs
            %li
              %a{:href => ""} Profile
            %li
              %a{:href => ""} Contacts
            %li
              %a{:href => ""} Mailbox
            %li.divider
            %li
              %a{:href => ""} Logout
        .logo-element
          IN+

      %li{:class => "#{active_controller?('dashboards')}"}
        %a{:href => ""}
          %i.fa.fa-th-large
          %span.nav-label{"data-i18n" => "nav.dashboard"} Dashboards
      %li
        %a#manage{href: "#"}
          %i.fa.fa-cogs
          %span.nav-label= t('.manage')
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li{ class: '' }
            = link_to t('.agencies'), '#'
          %li{ class: '' }
            = link_to t('.departments'), '#'

      

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Portfolio
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://js.stripe.com/v2/', 'application'
    = csrf_meta_tags
    = tag :meta, name: 'stripe-key', content: STRIPE_PUBLIC_KEY
  %body{ id: "#{controller_name}-#{action_name}", class: 'fixed-sidebar pace-done' }
    #wrapper{ data: flash_alert }
      = render 'layouts/sidebar'
      #page-wrapper.gray-bg
        = render 'layouts/navigation'
        .padding-bottom
          = yield
        = render 'layouts/footer'

app/views/plans/index.haml
.table-responsive
  %table.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Price
        %th
    %tbody
      - @plans.each do |plan|
        %tr
          %td= plan.name
          %td= number_to_currency(plan.price)
          %td
            = link_to new_plan_subscription_path(plan), class: 'btn btn-success btn-xs' do
              Subscribe

app/views/subscriptions/_form.haml
= simple_form_for([@plan, @subscription]) do |f|
  = f.hidden_field :stripe_card_token
  .field
    = f.input :name
    = f.input :email
  .field
    = label_tag :card_number, 'Card Number'
    = text_field_tag :card_number, nil, name: nil
  .field
    = label_tag :card_code, 'Card Code (CVV)'
    = text_field_tag :card_code, nil, name: nil
  .field
    = label_tag :card_code, 'Card Expired Date'
    = select_month nil, { add_month_numbers: true }, { name: nil, id: 'card_month' }
    = select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { name: nil, id: 'card_year' }
  #stripe_error
    %noscript Javascript is not enabled
  .actions
    = f.submit 'Subscribe', class: 'btn btn-primary btn-sm'

app/views/subscriptions/edit.haml
%h4 Edit Subscription
= render 'form'

app/views/subscriptions/new.haml
%h4 New Subscription
= render 'form'

app/views/subscriptions/show.haml
%p= "Name : #{@subscription.name}"
%p= "Email : #{@subscription.email}"
%p= link_to 'Edit', edit_plan_subscription_path(@plan, @subscription), class: 'btn btn-warning btn-xs'
%br
%p= link_to 'Home', root_path, class: 'btn btn-default'

app/views/welcome/index.haml
.row
  .col-xs-12
    %h1 Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.